apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo-inbound.fullname" . }}
spec:
  serviceName: {{ include "mongo-inbound.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongo-inbound.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo-inbound.fullname" . }}
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.auth.username | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.auth.username | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.auth.database | quote }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-inbound-pvc

