apiVersion: v1
data:
  DB_DRIVER: b3JnLnBvc3RncmVzcWwuRHJpdmVy
  DB_PASSWORD: dXNlcjE=
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtdXNlci5wb3N0Z3Jlczo1NDMzL3VzZXJfZGI=
  DB_USERNAME: dXNlcjE=
  REDIS_HOST: cmVkaXMtY2x1c3Rlci5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  REDIS_PASSWORD: dXNlcjE=
  REDIS_PORT: NjM3OQ==
  SERVER_PORT: MTA0MQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: user-service-secret
  namespace: wms
