replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

auth:
  username: "user1"
  password: "user1"
  database: "inbound_db"

service:
  type: ClusterIP
  port: 27018

persistence:
  enabled: true
  existingClaim: mongo-outbound-pvc
  size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
