replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

auth:
  username: "user1"
  password: "user1"
  database: "outbound_db"

persistence:
  enabled: true
  existingClaim: "mongo-outbound-pvc"
  storageClass: "nfs-storage"
  size: 10Gi
