apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1040
      targetPort: 1040
  type: {{ .Values.service.type }}
