apiVersion: v2
name: inbound
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"

replicaCount: 1

image:
  repository: chamchimayo/inbound-service
  tag: "v10.0.13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1050
  targetPort: 1050

env:
  SERVER_PORT: 1050

  # MongoDB 연결 설정
  MONGO_HOST: mongo-inbound.mongo.svc.cluster.local
  MONGO_PORT: 27017
  MONGO_USER: user1
  MONGO_PASS: user1
  MONGO_DB: inbound_db
  MONGO_AUTH_DB: admin

  # Kafka 연결 설정
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  SPRING_KAFKA_TOPIC_INBOUND_CREATED: "inbound-created"
  SPRING_KAFKA_TOPIC_INVENTORY_UPDATED: "inventory-updated"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "inbound-group"