apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: monitoring  # 서비스 계정 연결
      securityContext:
        fsGroup: 0  # Pod 수준에서 fsGroup을 설정
      containers:
        - name: fluent-bit
          image: amazon/aws-for-fluent-bit:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIA34AMDDJLFTNAAK7D"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
          securityContext:
            runAsUser: 0  # root 사용자로 실행 (권한 문제 해결)
            runAsGroup: 0  # root 그룹으로 실행
          volumeMounts:
            - name: config-volume
              mountPath: /etc/fluent-bit/fluent-bit.conf
              subPath: fluent-bit.conf

            - name: filter-lua-volume
              mountPath: /etc/fluent-bit/filter.lua
              subPath: filter.lua

            - name: inventory-log
              mountPath: /helm-charts/monitoring/log
          command: ["/fluent-bit/bin/fluent-bit"]
          args:
            - -c
            - /etc/fluent-bit/fluent-bit.conf
      volumes:
        - name: config-volume
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf

        - name: filter-lua-volume
          configMap:
            name: fluent-bit-config
            items:
              - key: filter.lua
                path: filter.lua

        - name: inventory-log
          hostPath:
            path: /helm-charts/monitoring/log
            type: DirectoryOrCreate
