# Kong 기본 설정
replicaCount: 2

# PostgreSQL 제거
postgresql:
  enabled: false  # ✅ PostgreSQL 비활성화

# Kong 데이터베이스 설정 (DBless 모드)
database:
  enabled: false
  type: "off"

# Kong 서비스 설정
proxy:
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  https:
    enabled: true
    servicePort: 443
    containerPort: 8443

admin:
  enabled: false  # ✅ Admin API 사용 안함

# Kong 환경 변수 (DB 없이 실행)
extraEnvVars:
  - name: KONG_DATABASE
    value: "off"
  - name: KONG_DECLARATIVE_CONFIG
    value: "/opt/kong/kong.yml"
  - name: KONG_SSL_CERT
    value: "/etc/kong/ssl/tls.crt"  # ✅ Secret을 통한 인증서 적용
  - name: KONG_SSL_CERT_KEY
    value: "/etc/kong/ssl/tls.key"  # ✅ Secret을 통한 키 적용

# Kong Ingress 설정
ingressController:
  enabled: true
  installCRDs: false
  ingressClassName: "nginx"
  admin:
    enabled: false
  proxy:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    tls:
      enabled: true
      secretName: kong-tls
    hosts:
      - api.sol-wms.store

# Kafka 연동 설정 (JWT 인증 이벤트 처리)
kafka:
  enabled: true
  bootstrapServers: "my-cluster-kafka-0.kafka.svc.cluster.local:9092,my-cluster-kafka-1.kafka.svc.cluster.local:9092"
  topic: "kong_jwt_events"
  securityProtocol: "PLAINTEXT"

