apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  postgresql.conf: |
    port = 5433
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
