apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  postgresql.conf: |
    port = {{ .Values.primary.containerPorts.postgresql }}
    max_connections = 100
    shared_buffers = 128MB
