apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-user-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0fbd3fc802bc4d5fd
    fsType: ext4
