apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  type: ClusterIP
  selector:
    app: postgres-user
  ports:
    - port: 5433
      targetPort: 5433
      protocol: TCP
      name: postgres
