apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-user
spec:
  serviceName: postgres-user
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_DB
              value: "user_db"
            - name: POSTGRES_USER
              value: "user1"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/postgres
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          volumeMounts:
            - name: data-storage
              mountPath: /var/lib/postgresql/data/postgres
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: postgres-user-pvc
        - name: config
          configMap:
            name: postgres-config
            items:
              - key: postgresql.conf
                path: postgresql.conf
