# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat-cluster-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumes
      - persistentvolumeclaims
      - replicationcontrollers
      - resourcequotas
      - secrets
      - storageclasses
      - poddisruptionbudgets
      - volumes
      - endpoints
      - ingresses
    verbs:
      - list
      - get

