apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: wms
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: inbound-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          readinessProbe:
            httpGet:
              path: /api/inbound/actuator/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/inbound/actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: MONGO_HOST
              value: "{{ .Values.env.MONGO_HOST }}"
            - name: MONGO_PORT
              value: "{{ .Values.env.MONGO_PORT }}"
            - name: MONGO_USER
              value: "{{ .Values.env.MONGO_USER }}"
            - name: MONGO_PASS
              value: "{{ .Values.env.MONGO_PASS }}"
            - name: MONGO_DB
              value: "{{ .Values.env.MONGO_DB }}"
            - name: MONGO_AUTH_DB
              value: "{{ .Values.env.MONGO_AUTH_DB }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
            - name: SPRING_KAFKA_TOPIC_INBOUND_CREATED
              value: "{{ .Values.env.SPRING_KAFKA_TOPIC_INBOUND_CREATED }}"
            - name: SPRING_KAFKA_TOPIC_INVENTORY_UPDATED
              value: "{{ .Values.env.SPRING_KAFKA_TOPIC_INVENTORY_UPDATED }}"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "{{ .Values.env.SPRING_KAFKA_CONSUMER_GROUP_ID }}"
