apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: wms
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
