apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-inventory.fullname" . }}
spec:
  serviceName: {{ include "postgres-inventory.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres-inventory.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-inventory.fullname" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata    # ✅ PGDATA는 하위 경로 지정
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql            # ✅ 여기까지만 마운트 (EBS에 lost+found 대응)
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}

