apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-inventory.fullname" . }}
spec:
  serviceName: {{ include "postgres-inventory.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres-inventory.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-inventory.fullname" . }}
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "user1"
            - name: POSTGRES_PASSWORD
              value: "user1"
            - name: POSTGRES_DB
              value: "inventory_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:  # ✅ 기존 PVC를 직접 참조하여 사용
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-inventory-pvc  # ✅ 기존 PVC 사용
