replicaCount: 1

image:
  repository: chamchimayo/inbound-service
  tag: "v0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1051

env:
  SERVER_PORT: 1051
  MONGO_HOST: mongo-inbound.mongo.svc.cluster.local
  MONGO_PORT: 27018
  MONGO_USER: user1
  MONGO_PASS: user1
  MONGO_DB: inbound_db
  MONGO_AUTH_DB: admin

