apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    dir /data
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000

