replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

auth:
  username: "user1"
  password: "user1"
  database: "inventory_db"

persistence:
  enabled: true
  storageClass: "gp2"   # AWS에서 동작하는 StorageClass (클러스터에 따라 gp2도 가능)
  size: 20Gi
