global:
  storageClass: ""

fullnameOverride: postgres-inventory

architecture: standalone

auth:
  enablePostgresUser: true
  postgresPassword: soldesk
  username: user1
  password: user1
  database: inventory_db

primary:
  persistence:
    enabled: false
    storageClass: ""
    size: 20Gi
  
  containerPorts:
    postgresql: 5432

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

service:
  type: ClusterIP
  port: 5432