global:
  storageClass: ""

fullnameOverride: postgres-user

architecture: standalone

auth:
  enablePostgresUser: true
  postgresPassword: soldesk
  username: user1
  password: user1
  database: user_db

primary:
  persistence:
    enabled: true
    storageClass: ""
    size: 20Gi
  
  containerPorts:
    postgresql: 5433
  
  extendedConfiguration: |
    port = 5433

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

service:
  type: ClusterIP
  port: 5433