apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-outbound.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 27018
      targetPort: 27018
  selector:
    app: {{ include "mongo-outbound.fullname" . }}
